# Automatically generated by the steam_store_info.py script on 2024-03-09
from enum import Enum

STEAM_IMG_BASE_URL = "https://store.steampowered.com/"


class SteamCategory(Enum):
    def __new__(cls, value, display_name, icon_url):
        entry = object.__new__(cls)
        entry._value_ = value
        entry.display_name = display_name
        entry.icon_url = icon_url
        return entry

    MULTI_PLAYER = 1, "Multi-player", "public/images/v6/ico/ico_multiPlayer.png"
    SINGLE_PLAYER = 2, "Single-player", "public/images/v6/ico/ico_singlePlayer.png"
    MODS_REQUIRES_HL2 = 6, "Mods (require HL2)", "public/images/ico/ico_mod_hl2.gif"
    MODS_REQUIRES_HL1 = 7, "Mods (require HL1)", "public/images/ico/ico_mod_hl.gif"
    VAC_ENABLED = 8, "Valve Anti-Cheat enabled", "public/images/v6/ico/ico_vac.png"
    CO_OP = 9, "Co-op", "public/images/v6/ico/ico_coop.png"
    GAME_DEMO = 10, "Game demo", "public/images/ico/ico_demo.gif"
    CAPTIONS = 13, "Captions available", "public/images/v6/ico/ico_cc.png"
    COMMENTARY = 14, "Commentary available", "public/images/v6/ico/ico_commentary.png"
    STATS = 15, "Stats", "public/images/v6/ico/ico_stats.png"
    INCLUDES_SOURCE_SDK = 16, "Includes Source SDK", "public/images/v6/ico/ico_sdk.png"
    INCLUDES_LEVEL_EDITOR = 17, "Includes level editor", "public/images/v6/ico/ico_editor.png"
    CONTROLLER_ENABLED = 18, "Partial Controller Support", "public/images/v6/ico/ico_partial_controller.png"
    MODS = 19, "Mods", "public/images/v6/ico/ico_sdk.png"
    MMO = 20, "MMO", "public/images/v6/ico/ico_multiPlayer.png"
    DLC = 21, "Downloadable Content", "public/images/v6/ico/ico_dlc.png"
    STEAM_ACHIEVEMENTS = 22, "Steam Achievements", "public/images/v6/ico/ico_achievements.png"
    STEAM_CLOUD = 23, "Steam Cloud", "public/images/v6/ico/ico_cloud.png"
    SHARED_SPLIT_SCREEN = 24, "Shared/Split Screen", "public/images/v6/ico/ico_coop.png"
    STEAM_LEADERBOARDS = 25, "Steam Leaderboards", "public/images/v6/ico/ico_leaderboards.png"
    CROSS_PLATFORM_MULTIPLAYER = 27, "Cross-Platform Multiplayer", "public/images/v6/ico/ico_multiPlayer.png"
    FULL_CONTROLLER_SUPPORT = 28, "Full controller support", "public/images/v6/ico/ico_controller.png"
    STEAM_TRADING_CARDS = 29, "Steam Trading Cards", "public/images/v6/ico/ico_cards.png"
    STEAM_WORKSHOP = 30, "Steam Workshop", "public/images/v6/ico/ico_workshop.png"
    VR_SUPPORT = 31, "VR Support", "public/images/v6/ico/VRIcon.png"
    ASYNC_GAME_NOTIFICATIONS = 32, "Steam Turn Notifications", "public/images/v6/ico/ico_turn_notifications.png"
    IN_APP_PURCHASES = 35, "In-App Purchases", "public/images/v6/ico/ico_cart.png"
    ONLINE_PVP = 36, "Online PvP", "public/images/v6/ico/ico_multiPlayer.png"
    SHARED_SPLIT_SCREEN_PVP = 37, "Shared/Split Screen PvP", "public/images/v6/ico/ico_multiPlayer.png"
    ONLINE_CO_OP = 38, "Online Co-op", "public/images/v6/ico/ico_coop.png"
    SHARED_SPLIT_SCREEN_CO_OP = 39, "Shared/Split Screen Co-op", "public/images/v6/ico/ico_coop.png"
    STEAMVR_COLLECTIBLES = 40, "SteamVR Collectibles", "public/images/v6/ico/ico_collectibles.png"
    REMOTE_PLAY_ON_PHONE = 41, "Remote Play on Phone", "public/images/v6/ico/ico_remote_play.png"
    REMOTE_PLAY_ON_TABLET = 42, "Remote Play on Tablet", "public/images/v6/ico/ico_remote_play.png"
    REMOTE_PLAY_ON_TV = 43, "Remote Play on TV", "public/images/v6/ico/ico_remote_play.png"
    REMOTE_PLAY_TOGETHER = 44, "Remote Play Together", "public/images/v6/ico/ico_remote_play_together.png"
    LAN_PVP = 47, "LAN PvP", "public/images/v6/ico/ico_multiPlayer.png"
    LAN_CO_OP = 48, "LAN Co-op", "public/images/v6/ico/ico_coop.png"
    PVP = 49, "PvP", "public/images/v6/ico/ico_multiPlayer.png"
    HIGH_QUALITY_AUDIO = 50, "Additional High-Quality Audio", "public/images/v6/ico/ico_hdaudio.png"
    STEAM_CHINA_WORKSHOP = 51, "Steam Workshop", "public/images/v6/ico/ico_workshop.png"
    TRACKED_MOTION_CONTROLLER = 52, "Tracked Controller Support", "public/images/v6/ico/ico_vr_input_motion.png"
    VR_SUPPORTED = 53, "VR Supported", "public/images/v6/ico/ico_vr_support.png"
    VR_ONLY = 54, "VR Only", "public/images/v6/ico/ico_vr_support.png"
    HDR = 61, "HDR available", "public/images/v6/ico/ico_hdr.png"
    FAMILY_SHARING = 62, "Family Sharing", "public/images/v6/ico/ico_familysharing.png"
