import json
import logging
import os
import re
from argparse import ArgumentParser
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from helpers import TmpFile
from platforms.steam import SteamAPI

DEST_FILE = Path(__file__).parent.parent / 'platforms/steam_info.py'


@dataclass
class Category:
    id: int
    code: str
    name: str
    icon: str


def run(steam_api_key):
    client = SteamAPI(steam_api_key)
    print("Retrieving Steam categories…", end=" ")
    data = client.get_steam_categories()
    print("done")

    categories = []
    for c in sorted(data, key=lambda c: c['categoryid']):
        uc_name = '_'.join(part.upper() for part in re.findall(r"\w+", c['internal_name']))
        categories.append(Category(c['categoryid'], uc_name, c['display_name'], c['image_url']))

    joiner = '\n    '
    time = datetime.now().strftime("%Y-%m-%d")
    contents = f'''# Automatically generated by the {Path(__file__).name} script on {time}
from enum import Enum

STEAM_IMG_BASE_URL = "https://store.steampowered.com/"


class SteamCategory(Enum):
    def __new__(cls, value, display_name, icon_url):
        entry = object.__new__(cls) 
        entry._value_ = value
        entry.display_name = display_name
        entry.icon_url = icon_url
        return entry
    
    {joiner.join(f'{c.code} = {c.id}, {json.dumps(c.name)}, {json.dumps(c.icon)}' for c in categories)}
'''
    with TmpFile(DEST_FILE) as path, path.open('wt') as fh:
        fh.write(contents)
    print(f'Saved {len(categories)} categories in {DEST_FILE}')


if __name__ == '__main__':
    parser = ArgumentParser(description='Generate Steam Store Info')
    env_steam_api_key = os.environ.get('STEAM_API_KEY')
    parser.add_argument('--steam-api-key',
                        help='Steam Web API key, get one here: https://steamcommunity.com/dev/apikey',
                        required=env_steam_api_key is None, default=env_steam_api_key)
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO)
    run(**vars(args))
